spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 7cb17277423ef13c0257
            client-secret: ecf02bb7dcfa1dd944cc595a0c25108617365626

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG

#spring.security.oauth2.client.registration.github.client-id = 3e23a2c6d4dfda3443b4
#spring.security.oauth2.client.registration.github.client-secret = a12a23d213319bbb88bf620ea92569bbb0ccb381
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework = DEBUG
